---
apiVersion: v1
kind: Service
metadata:
  name: carts
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: carts
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80