---
apiVersion: v1
kind: Service
metadata:
  name: user-db
  labels:
    name: user-db
  namespace: sock-shop
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: user-db
  ports:
    # the port that this service should serve on
  - port: 27017
    targetPort: 27017