---
apiVersion: v1
kind: Service
metadata:
  name: session-db
  labels:
    name: session-db
  namespace: sock-shop
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: session-db
  ports:
    # the port that this service should serve on
  - port: 6379
    targetPort: 6379