
output "cluster_name" {
  description = "Kubernetes Cluster Name"
  value       = var.cluster-name
}

output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = aws_eks_cluster.main.endpoint
}

output "region" {
  description = "AWS region"
  value       = var.region
}

output "kubeconfig" {
  description = "kubectl config as generated by the module."
  value       = local.kubeconfig
}


# output "config_map_aws_auth" {
#   description = "A kubernetes configuration to authenticate to this EKS cluster."
#   value       = module.eks.config_map_aws_auth
# }