apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: prod-jenkins
spec:
  service:
    type: NodePort
    port: 8080
  master:
    basePlugins:
    - name: kubernetes
      version: "1.25.2"
    - name: workflow-job
      version: "2.40"
    - name: workflow-aggregator
      version: "2.6"
    - name: git
      version: "4.2.2"
    - name: job-dsl
      version: "1.77"
    - name: configuration-as-code
      version: "1.47"
    - name: kubernetes-credentials-provider
      version: "0.13"
    containers:
    - name: jenkins-master
      image: jenkins/jenkins:lts
      imagePullPolicy: Always
      env:
      - name: JENKINS_OPTS
        value: --prefix=/jenkins
      livenessProbe:
        failureThreshold: 12
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 80
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      readinessProbe:
        failureThreshold: 3
        httpGet:
          path: /login
          port: http
          scheme: HTTP
        initialDelaySeconds: 30
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 1
      resources:
        limits:
          cpu: 1500m
          memory: 3Gi
        requests:
          cpu: "1"
          memory: 500Mi
      securityContext:
        runAsUser: 1000
        fsGroup: 1000
  seedJobs:
  - id: jenkins-operator
    targets: "apps/jenkins-seed-jobs/hello-world/jobs/hello_world.jenkins"
    description: "Hello World Demo - Jenkins Operator"
    repositoryBranch: dev
    repositoryUrl: https://github.com/Joeltrane/architecture-demo.git
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: jenkins-server-ing
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - http:
      paths:
      - path: /jenkins
        backend:
          serviceName: jenkins-operator-http-prod-jenkins
          servicePort: 8080
