---
apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    name: orders
  namespace: sock-shop
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: orders
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80
