---
apiVersion: v1
kind: Service
metadata:
  name: front-end
  labels:
    name: front-end
  namespace: sock-shop
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: front-end
  ports:
  - port: 80
    targetPort: 8079
    nodePort: 30001
