---
apiVersion: v1
kind: Service
metadata:
  name: catalogue
  labels:
    name: catalogue
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalogue
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80

