---
apiVersion: v1
kind: Service
metadata:
  name: catalogue-db
  labels:
    name: catalogue-db
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalogue-db
  ports:
    # the port that this service should serve on
  - port: 3306
    targetPort: 3306