---
apiVersion: v1
kind: Service
metadata:
  name: queue-master
  labels:
    name: queue-master
  annotations:
    prometheus.io/path: "/prometheus"
  namespace: sock-shop
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: queue-master
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: 80